server:
  port: 1027

spring:
  application:
    name: vcloud-oauth-server
  redis:
    database: 0
#    host: 192.168.101.102
    host: localhost
    port: 6379

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:root@127.0.0.1:1025/eureka/
    registry-fetch-interval-seconds: 10
    #enabled: false

logging:
  level:
    com:
      study:
        vcloud:
          oauth: debug