server:
  port: 9999

spring:
  application:
    name: vcloud-zuul-server

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://root:root@127.0.0.1:1025/eureka/
    registry-fetch-interval-seconds: 10

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: vcloud-user-server,vcloud-oauth-server
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    vcloud-user-server:
      path: /user/**
      serviceId: vcloud-user-server
      stripPrefix: true
    vcloud-oauth-server:
      path: /oauth/**
      serviceId: vcloud-oauth-server
      stripPrefix: true
  sensitive-headers:  #为空解决转发服务token丢失


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000


logging:
  level:
    com:
      pwl:
        vcloud:
          zuul: debug

security:
  auth:
    server: http://127.0.0.1:1027
  oauth2:
    client:
      client-id: client_id
      client-secret: client_secret
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check_token
#      jwt:
#        key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

#不需要鉴权的url
urls:
  anon:
    - /oauth/**
    - /user/common/**



