server:
  port: 8053

spring:
  application:
    name: config-single-server-git  # 应用名称
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/huzhicheng/config-only-a-demo #配置文件所在仓库
          uri: https://github.com/cjeanGitHub/SpringCloudConfig #配置文件所在仓库
          username: CjeanGitHub
          password: cdl756560360
#          default-label: master #配置文件分支
          search-paths: config-repo  #配置文件所在根目录
